### ISSUE TITLE
Who actually made the pubg cog

### ISSUE THREAD

**Issue by Stylite** [Belos/belos-cogs#1]
That doesnt look like your work at all.

**Comment by pgaetani** [comment]
Who made all of your cogs, actually.

**Comment by Shigbeard** [comment]
Everyone but him apparently.

**Comment by Belos** [comment]
the author of pubg is called aikaterna you can find his work here https://github.com/aikaterna/aikaterna-cogs/

**Comment by MiniJennJenn** [comment]
Try again and tell us who the author of the PUBG cog is. There is no PUBG in that repo and aikaterna is one of our patrons. We're aware that he isn't the author.

**Comment by Shigbeard** [comment]
And even if it was made by aikaterna, you didn't credit them. As seen in commit e899dbc, even though you deleted the pubg cog, from your repo, it had you credited as the author, which is a major no-go.

If you wish to feature other developer's cogs on your repo, you should ask them, and no matter their response, you should NEVER replace credits to them with your name, as that is stealing.
